Handle invalid options/parameters as errors

diff --git a/.github/release b/.github/release
--- a/.github/release
+++ b/.github/release
@@ -21,6 +21,9 @@ ANSI_YELLOW="\033[33m"
 # verbosity
 STDOUT=/dev/stdout
 
+# script reference
+SELF="$(basename $0)"
+
 # parse args
 while [ $# -ne 0 ]
 do
@@ -43,7 +46,12 @@ do
       ;;
 
     -*|--*)
-      echo >&2 "Invalid option $1"
+      echo >&2 "${SELF}: Invalid option $1"
+      exit 1
+      ;;
+
+    *)
+      echo >&2 "${SELF}: Invalid parameter $1"
       exit 1
       ;;
 
diff --git a/linux/packaging/publish b/linux/packaging/publish
--- a/linux/packaging/publish
+++ b/linux/packaging/publish
@@ -10,6 +10,9 @@
 # errexit
 set -e
 
+# script reference
+SELF="$(basename $0)"
+
 # parse args
 while [ $# -ne 0 ]
 do
@@ -27,11 +30,13 @@ do
       ;;
 
     -*|--*)
-      shift
+      echo >&2 "${SELF}: Invalid option $1"
+      exit 1
       ;;
 
     *)
-      shift
+      echo >&2 "${SELF}: Invalid parameter $1"
+      exit 1
       ;;
 
   esac
