Remove built-in version extraction/incrementation

diff --git a/.github/release b/.github/release
--- a/.github/release
+++ b/.github/release
@@ -59,16 +59,13 @@ do
 
 done
 
+# ensure requisite meta
+test -z "$TAG_NAME" && {
+  echo >&2 "${ANSI_RED}${SELF}: Missing required parameter TAG${ANSI_RESET}"; exit 1; }
+
 # ensure requisite files
 test -f releases/windows/aliases.cab && test -f releases/linux/sbin.tar && \
   test -f releases/linux/bin.tar || { echo >&2 "${ANSI_RED}Missing requisit file(s)${ANSI_RESET}"; exit 1; }
-
-# tag (latest++)
-test -z "$TAG_NAME" && TAG_NAME="$(curl --silent --fail --location --show-error --header "Authorization: token $GITHUB_TOKEN" --url "https://api.github.com/repos/$REPOSITORY/tags" \
-  | jq --raw-output '.[0]["name"] // "v0" | match("v(\\d+\\.?\\d*?)(\\.\\d*)?$") | .["captures"][0]["string"] | tonumber + .1 | "v" + tostring')"
-
-# strip preceding decimals
-TAG_NAME="$(expr substr $TAG_NAME 1 4)"
 
 echo 1>$STDOUT "${ANSI_YELLOW}Preparing release ${TAG_NAME}${ANSI_RESET}"
 
