Remove linux artefact deployment to GitHub releases

diff --git a/.github/release b/.github/release
--- a/.github/release
+++ b/.github/release
@@ -64,8 +64,8 @@ test -z "$TAG_NAME" && {
   echo >&2 "${ANSI_RED}${SELF}: Missing required parameter TAG${ANSI_RESET}"; exit 1; }
 
 # ensure requisite files
-test -f releases/windows/aliases.cab && test -f releases/linux/sbin.tar && \
-  test -f releases/linux/bin.tar || { echo >&2 "${ANSI_RED}Missing requisit file(s)${ANSI_RESET}"; exit 1; }
+test -f releases/windows/aliases.cab || {
+  echo >&2 "${ANSI_RED}Missing requisit file(s)${ANSI_RESET}"; exit 1; }
 
 echo 1>$STDOUT "${ANSI_YELLOW}Preparing release ${TAG_NAME}${ANSI_RESET}"
 
@@ -84,15 +84,3 @@ echo 1>$STDOUT "${ANSI_YELLOW}Uploading artifact aliases.cab${ANSI_RESET}"
 # upload aliases.cab
 curl --silent --fail --show-error --request POST --header "Authorization: token $GITHUB_TOKEN" --header "Content-Type: application/vnd.ms-cab-compressed" \
   --data-binary "@releases/windows/aliases.cab" --output /dev/null --url "https://uploads.github.com/repos/$REPOSITORY/releases/$RELEASE_ID/assets?name=aliases.cab&label=Windows%20Binaries"
-  
-echo 1>$STDOUT "${ANSI_YELLOW}Uploading artifact sbin.tar${ANSI_RESET}"
-
-# upload sbin.tar
-curl --silent --fail --show-error --request POST --header "Authorization: token $GITHUB_TOKEN" --header "Content-Type: application/x-tar" \
-  --data-binary "@releases/linux/sbin.tar" --output /dev/null --url "https://uploads.github.com/repos/$REPOSITORY/releases/$RELEASE_ID/assets?name=sbin.tar&label=Linux%20System%20Binaries"
-
-echo 1>$STDOUT "${ANSI_YELLOW}Uploading artifact bin.tar${ANSI_RESET}"
-
-# upload bin.tar
-curl --silent --fail --show-error --request POST --header "Authorization: token $GITHUB_TOKEN" --header "Content-Type: application/x-tar" \
-  --data-binary "@releases/linux/bin.tar" --output /dev/null --url "https://uploads.github.com/repos/$REPOSITORY/releases/$RELEASE_ID/assets?name=bin.tar&label=Linux%20Binaries"
